import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import AuthenticatorWrapper from "./AuthenticationWrapper";
import "@aws-amplify/ui-react/styles.css";

const inter = Inter({ subsets: ["latin"] });

import "@/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Mapsterious 2.0</title>
      </head>
      <body className={inter.className}>
        <AuthenticatorWrapper>{children}</AuthenticatorWrapper>
      </body>
    </html>
  );
}
